# --- paths ---
pretrained_model_name_or_path: "Qwen/Qwen-Image-Edit"
img_dir: "/workspace/qwen-image-training/extracted_dataset/train/images"
control_dir: "/workspace/qwen-image-training/extracted_dataset/train/control"
output_dir: "/workspace/qwen-image-training/outputs/qwen_edit_lora_ref"
logging_dir: "logs"

# --- training ---
resolution: 1024
train_batch_size: 2
gradient_accumulation_steps: 2
max_train_steps: 8000
learning_rate: 1e-4
lr_scheduler: cosine
lr_warmup_steps: 200
seed: 42
mixed_precision: bf16

# --- LoRA config ---
lora_rank: 32
lora_alpha: 32
lora_dropout: 0.0

# --- misc ---
checkpointing_steps: 500
validation_steps: 1000
log_steps: 50
