# global options
resolutions      = [512]
enable_ar_bucket = true
min_ar           = 0.5
max_ar           = 2.0
num_ar_buckets   = 7
frame_buckets    = [1]

[[directory]]
# images to be edited (caption files share the same stem)
path          = "/workspace/qwen-image-training/data/breast-edit-dataset/output"
# base images fed to the UNet
source_path   = "/workspace/qwen-image-training/data/breast-edit-dataset/input"
# images showing the desired edit, passed to the text encoder
reference_path = "/workspace/qwen-image-training/data/breast-edit-dataset/breast"
num_repeats   = 1
