# paths
output_dir = "/workspace/qwen-image-training/configs/output"
dataset    = "/workspace/qwen-image-training/configs/dataset.toml"

# training settings
epochs                     = 1000
micro_batch_size_per_gpu   = 1
gradient_accumulation_steps = 4
pipeline_stages            = 1
gradient_clipping          = 1

# evaluation
eval_every_n_epochs        = 1
eval_before_first_step     = true
eval_micro_batch_size_per_gpu = 1
eval_gradient_accumulation_steps = 1

# misc
save_every_n_epochs        = 5
checkpoint_every_n_minutes = 120
activation_checkpointing   = true
partition_method           = "parameters"
save_dtype                 = "bfloat16"
caching_batch_size         = 8
steps_per_print            = 1
blocks_to_swap             = 8

[model]
type                  = "qwen_image"
diffusers_path        = "/workspace/qwen-image-training/Qwen-Image-Edit"
dtype                 = "bfloat16"
transformer_dtype     = "float8"
timestep_sample_method = "logit_normal"

[adapter]
type = "lora"
rank = 32
dtype = "bfloat16"

[optimizer]
type         = "automagic"
weight_decay = 0.01

